name: Check format

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Show log
        run: git log -5

      - id: pdfium
        name: Get pdfium-binaries latest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: bblanchon
          repo: pdfium-binaries

      - id: check
        name: Get byrdocs-check release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: byrdocs
          repo: byrdocs-check

      - name: Download release
        run: |
          wget https://github.com/byrdocs/byrdocs-check/releases/download/${{ steps.check.outputs.release }}/check-pr
          chmod 777 check-pr

      - name: Check
        run: |
          ./check-pr -d ./metadata
